### ISSUE TITLE
Monday is holiday in .de

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#107]
That's @dignifiedquire @haadcode and myself. I'll post my sprint update some time during the weekend, and the infrastructure hangout will have to move -- Tuesday same time (1800Z/2000CEST) is cool.

![dahme](http://www.unsere-landschaften.de/bilder/Fruehling-am-Ufer-der-Dahme-bei-Berlin-Gruenau-6177.jpg)

**Comment by RichardLitt** [comment]
@jbenet Can we move the whole sprint to Tuesday?

Wish we had some advanced notice -- plans on Tuesday may already be unmoveable.

**Comment by dignifiedquire** [comment]
@richardlitt ping me I can send you a calender with German holidays

**Comment by lgierth** [comment]
Google calendar has holidays as separate calendars that you can include

**Comment by RichardLitt** [comment]
@dignifiedquire Cool. Ping you where? We should add these to the community calendars, maybe.

**Comment by jbenet** [comment]
We don't really observe holidays anywhere, because observing all would be difficult. We move when it's desired. So let's just move whatever you guys can't attend to Tuesday. But let's et advanced notice on this sort of thing-- we can't keep moving whole sprints so often and without advanced notice.

(Also, at this point, I don't have time Tuesday)

**Comment by dignifiedquire** [comment]
I'm around, so I don't mind if we move it or not

**Comment by haadcode** [comment]
I'll be around Monday for the sync. 

All said in this thread, we should figure this out for the future. Different countries, different holidays and we don't want to prevent people being able to have the holidays (and legally we can't). The public Google calendars for for holidays is a good start, AR least we're aware when the holidays are.

**Comment by haadcode** [comment]
Out of curiosity, how many public holidays USA has per year?

In Germany they vary between the states, in Berlin it's 9 this year (7 starting 2017).

**Comment by diasdavid** [comment]
We've 13 :D. 

There has been some syncs during public holidays here, but since I never really do holidays, I never brought it up. I totally understand that being able to take out these public holidays is important because typically it is when our friends and family also have some time off, making it a perfect day to hangout with everyone. For me, both Monday and Tuesday are good.

**Comment by lgierth** [comment]
I will be here for the hangouts after all (missing sync though, will post my update in a bit)

**Comment by RichardLitt** [comment]
Cool. We're having all of the hangouts today, so I consider this closed. Let us know if there are more in the future!
