### ISSUE TITLE
Establish a format for Distributed Quarterly Meetings

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#143]
Spinning this off from #142 so we can Establish a format for convening Distributed Quarterly IPFS Meetings.

**Comment by flyingzumwalt** [comment]
Declaring my skepticism up front: I'm not convinced that this can work, but I'm open to being convinced and certainly open to trying it.  For the IPFS community it might be an unavoidable necessity to have distributed meetings so that cost of travel isn't a barrier to participation in decision making.

My main concerns:
* With people spread across lots of time zones, it doesn't seem feasible to sustain multiple days of synchronous discussion and decision making.
* You lose the focus of everyone being in the same physical space together, which has huge impact on their attention
* You lose the social component of spending downtime socializing together, which is extremely important and valuable

Can anyone provide examples of organizations that have been able to successfully convene large distributed synchronous meetings and rely on them for things like roadmapping?

**Comment by RichardLitt** [comment]
How does Automattic do it? Does anyone know anyone working there?

**Comment by jbenet** [comment]
Some notes from the all-hands call on https://github.com/ipfs/pm/issues/141:

- There's a ton of questions as to whether this will be possible to do right (we all have a healthy amount of skepticism on this, because it's just so hard to pull this kind of meetings distributed)
- Definitely want to find successful examples before we jump into this.
  - Are there any strongly successful examples from standards groups like IETF and W3C? (there's many unsuccessful examples, and lots of successful in-person workshops)
- Is this the right format for this in the first place? (to be discussed in PMing) (@haadcode)
- Make sure that we are distributed entirely -- no halfway, because it creates a difference of access and logistical nightmares (@diasdavid)
- If we do this, we should try experimenting beforehand with a smaller-scale version (maybe a roadmapping meeting for multiformats or libp2p), to see how it could work and it would go. (@jbenet)
