### ISSUE TITLE
Sprint: Aug 22 → Aug 28

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#146]
# Sprint Aug 22

_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Endeavour         | Lead            | Time (PDT - **UTC/Z** - CEST) | Pad
:---------------: | :-------------: | :--------------------------: | :----:
All Hands Call   | @flyingzumwalt    | 9:00PDT **16:00Z** 18:00CEST  | [all-hands notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-all-hands)
js-ipfs                | @diasdavid       | 10:30PDT **17:30Z** 19:30CEST | [js-ipfs notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-js-ipfs)
go-ipfs               | @whyrusleeping  | 11:00PDT **18:00Z** 20:00CEST | [go-ipfs notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-go-ipfs)
libp2p            | @diasdavid      | 11:30PDT **18:30Z** 20:30CEST | [libp2p notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-libp2p)
interfaces repr   | @jbenet      | 12:00PDT **19:00Z** 21:00CEST | [interfaces-repr notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-interfaces-repr)
mediachain   | @jbenet      | 12:30PDT **19:30Z** 21:30CEST | [mediachain notes](https://public.etherpad-mozilla.org/p/ipfs-2016-08-22-mediachain)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by flyingzumwalt** [comment]
@parkan has proposed a Mediachain collaboration call (see #145). Should we add that to the day's agenda? Discuss it in the all-hands?

**Comment by flyingzumwalt** [comment]
Adding coveralls & code coverage to the agenda for all-hands. Just want to check in about where we're at with this.

**Comment by jbenet** [comment]
I propose this discussion:

- "Representing Interfaces, in libp2p doc repos and more" specifically modules like: https://github.com/libp2p/interface-peer-routing. require(@diasdavid) hope(@whyrusleeping)

doesn't need to happen this week, nor on monday, but best for it to.

**Comment by diasdavid** [comment]
Sounds good @jbenet :) For everyone following, here is the list of interfaces already started/written:

- https://github.com/libp2p/interface-transport
- https://github.com/libp2p/interface-stream-muxer
- https://github.com/libp2p/interface-connection
- https://github.com/libp2p/interface-record-store
- https://github.com/libp2p/interface-libp2p
- https://github.com/libp2p/interface-peer-routing

And for reference, here is the one we use for IPFS itself:

- https://github.com/ipfs/interface-ipfs-core

**Comment by flyingzumwalt** [comment]
Added "Representing Interfaces, in libp2p doc repos and more" to the all-hands agenda, which might just involve identifying when/where to push that process forward.

**Comment by flyingzumwalt** [comment]
Added "IPFS Tutorials in Gitbook form" as an agenda item for the all-hands.  I'll be proposing this format for assembling the new Tutorials (and gathering/re-formatting the existing ones) See: https://www.gitbook.com/book/flyingzumwalt/decentralized-web-primer/details

**Comment by lgierth** [comment]
@whyrusleeping @Kubuxu @jbenet and I should talk about a vulnerability report we got, maybe the 17:00Z slot?

**Comment by parkan** [comment]
Hello from team mediachain! Would love to get the following on the agenda:

- large dataset providing: chatty provide on add, direct improvements, workarounds (add w/o provide, alt. routing schemes)
- dataset add w/o copy: (re: https://github.com/ipfs/go-ipfs/issues/875)
- IPLD status/work needed (we want to help out!)

**Comment by jbenet** [comment]
@parkan great! would a call at 3:30p work for you?

**Comment by parkan** [comment]
@jbenet sure, works for me

**Comment by jbenet** [comment]
ok great. we'll add that call at 3:30p. I updated the schedule: https://github.com/ipfs/pm/issues/146#issue-172250678

**Comment by parkan** [comment]
@jbenet what do I dial into? should I get the url from IRC?

**Comment by RichardLitt** [comment]
Yeah, I'll throw it in IRC.

**Comment by parkan** [comment]
Good chat, cleared a lot of things up, have a path forward now (short-term). Thanks again!

One small thing: @vyzo is in EEST and having him participate in the future will be very valuable, is it possible to move the call up? We can likely do another day too, if the earlier hours are too packed.

**Comment by kevina** [comment]
@parkan @whyrusleeping I was looking over the notes to the mediachain call and I would like to clarify one point concerning ipfs/go-ipfs#875: I have only really broken compatibility once due to the datastore key change and I provided an upgrade path.  (In the very early stage I might have changed the format a bit more, but that was well before I created ipfs/go-ipfs#2364.)

**Comment by jbenet** [comment]
@kevina thoughts whether CIDv1 or your PR should land first? if CIDv1 simplifies a lot, worth waiting?

**Comment by kevina** [comment]
@jbenet, I would like to see my PR land first, CIDv1 will only simplify a small part that is now well isolated.  My PR requires a number of infrastructure changes that I will like to get in ASAP.

**Comment by whyrusleeping** [comment]
@kevina can you outline somewhere a revised list of tasks we need to do to get your PR in? things have changed a bit since you last updated your wiki landing page

**Comment by lgierth** [comment]
### @lgierth todo

- [ ] work through email backlog
- [ ] get up-to-date regarding project management, and comms
- [ ] fix ipfs.io/contact
- [ ] fix official go-ipfs docker image
- [x] send out new monthly infrastructure report (bling bling)
- [ ] update multigram spec draft
- [ ] start go-multigram implementation

**Comment by kevina** [comment]
@whyrusleeping yes I plan to in the next day or so

**Comment by diasdavid** [comment]
## js-ipfs goals for sprint

- [ ] Finish the pull-stream endeavour (@diasdavid, @dignifiedquire) - https://github.com/ipfs/js-ipfs/issues/403
  - [ ] Pass all the tests
  - [ ] Solve issue on spdy with pull-streams
  - [ ] Add documentation (@richardlitt, can you help us with this?)
  - [ ] Create JS knowledge base in ipfs/community with a FAQ and why we use pull-streams (link to the issue where the discussion happened)
  - [ ] Prioritize bitswap tests to pass with pull-streams
- [ ] Create a Connection Upgrade for half-closed streams - Similar to the length-prefix stream, just create a thing that encapsulates every packet with one byte, so that we have a way to signal that we are not going to send more data. Useful for libp2p-websockets and other transports that miss this feature.
- [ ] Drop the size of js-ipfs-api by shaving off some dependencies (@dignifiedquire)
  - https://github.com/ipfs/js-ipfs/issues/429
  - https://github.com/ipfs/js-ipfs/issues/398
  - https://github.com/ipfs/js-ipfs-api/issues/353
- [ ] Activate Code Coverage and CI in all the JS libp2p + ipfs repos (@richardlitt)
  - https://project-repos.ipfs.io/ (doesn't show the libp2p ones)
- [ ] Moar testing for js-ipfs
  - [ ] Network tests https://github.com/ipfs/js-ipfs/pull/299
  - [ ] HTTP-API tests https://github.com/ipfs/js-ipfs/issues/428
  - [ ] Tests that move a tooon of data over js-ipfs bitswap

**Comment by diasdavid** [comment]
# libp2p goals for this spring

- [ ] Finalize libp2p roadmap (@diasdavid)
  - [ ] Add more detailed and quantifiable milestones, tag them to the milestones of js-ipfs and go-ipfs, if needed
  - [ ] Set expecations (what will be done this quarter)
  - [ ] @lgierth to add the multigram goals
  - [ ] @jbenet and @whyrusleeping to review
- [ ] Make DHT "Providing records" faster
  - [ ] Create an issue with the ongoing work to make it faster, let others that are interested know (Mediachain) so they can follow the dev (@whyrusleeping)
- [ ] Review and give feedback on PubSub Harness (@whyrusleeping, @jbenet ) - https://github.com/gavinmcdermott/pubsub_testnet/issues/1
- libp2p.io (@richardlitt)
  - [ ] Set up a discussion, define goals (@richardlitt, @diasdavid)
  - [ ] Open issues with the goals so that they are trackable
  - [ ] Check the work that @kyledrake started and take it from there - https://github.com/libp2p/libp2p-website/pull/6

**Comment by RichardLitt** [comment]
What sort of documentation, @diasdavid?

**Comment by diasdavid** [comment]
@RichardLitt See:

- https://github.com/ipfs/js-ipfs/issues/362#issuecomment-237635915
- https://github.com/ipfs/js-ipfs/issues/403#issuecomment-238880369

**Comment by parkan** [comment]
@diasdavid I think the DHT point is missing "disable providing with ipfs add --local"

**Comment by diasdavid** [comment]
Thank you @parkan, added :)

**Comment by dignifiedquire** [comment]
@flyingzumwalt @RichardLitt can this be closed?
