### ISSUE TITLE
Define options for the Mechanics of Tracking Project Milestones

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#154]
Now that we have the _model_ for Project Management sketched out in the [draft PM process doc](https://github.com/ipfs/pm/blob/master/drafts/Project%20Management%20Process.md), we're ready to sketch out recommendations for the mechanics of how we apply the model in our projects. I'm especially eyeing the challenge of tracking milestones, which was discussed quite a bit in #125 and then tabled until we hammered out the model. Now I want to gather info about each of the options so it's easy to understand the pros & cons.

The [draft PM process doc](https://github.com/ipfs/pm/blob/master/drafts/Project%20Management%20Process.md) says that, regardless of the mechanics you choose, milestones have to have all of this info:
- description
- progress indicator
- list of goals
- estimated date of delivery (this one was [discussed quite a bit](https://github.com/ipfs/pm/pull/131/files/0fbf77efecf51695f4c9370c540e4d6727cda80d#diff-faaaa855bb08cd43cd9dfa87b532b534R58))

My question for any mechanics a project chooses, is: **If a project uses those mechanics to express milestones (ie. GH milestones, milestones as labels, etc) and has milestones that involve issues from multiple repos, is there a way to get a consolidated view of the information listed above?** How do we minimize the pain of providing, updating and/or finding and reviewing that info? Keep in mind that we need to aggregate this info into the Project Roadmap and (at least quarterly) aggregate it into the Organization Roadmap.

_It's clear that GH milestones could work great for projects that are contained within a single repo, but what about the projects that span multiple repos?_ Somewhere in all of these discussions & PR comments I thought @haadcode shared a link to something showing a GH milestone that includes issues from multiple GH repos and includes a progress indicator that includes all of the issues. Was I imagining that? Is that what [labels-and-milestones](https://github.com/haadcode/labels-and-milestones) does?

Alternatively, _If I express milestones as labels instead of using GH labels, where will I put this info? How do I get a progress indicator for that milestone?_ @diasdavid do you have suggestions?

cc @em-ly @jbenet

**Comment by jbenet** [comment]
Also to consider:
-  **Milestone Issues:** an issue used to express a milestone. It would contain links to its goals (issues). The title of the issue could be clear: `Milestone A: Some title` or `[Milestone 1]  Some title`
  - **Description:** would go in the body of the issue.
  - **List of goals:** a list of its goals (links to other issues)
  - **Progress indicator:** the list should have checkboxes, which will produce a progress indicator.
  - **ETA / Estimated Date of Delivery:** would be listed in the body of the issue.

**Comment by jbenet** [comment]
Also to consider:
-  **Github Issue as Milestone:** an issue used to express a milestone. It would contain links to its goals (issues). The title of the issue could be clear: `Milestone A: Some title` or `[Milestone 1]  Some title`
  - **Description:** would go in the body of the issue.
  - **List of goals:** a list of its goals (links to other issues)
  - **Progress indicator:** the list should have checkboxes, which will produce a progress indicator.
  - **ETA / Estimated Date of Delivery:** would be listed in the body of the issue.
  - Pros: 
    - Can be in one place, and link across to other repos.
    - Can be commented upon and discussed.
  - Cons:
    - the progress indicator is not as satisfying as the Github Milestones one
    - have to link issues in, instead of assigning them in the issue (i.e. github tuned for milestones)
  - Other:
    - This is very much like "Epic Issues" in ZenHub's model & mechanics: https://www.zenhub.com/blog/working-with-epics-in-github/

**Comment by jbenet** [comment]
Would be good if we had a similar listing to mine: https://github.com/ipfs/pm/issues/154#issuecomment-242233354 for the other popular ways to implement milestones here, just to be aware of them.

**Comment by jbenet** [comment]
-  **Github Issue as Goal:** an issue used to express a goal. It would contain the information and link to all relevant other material (goals, etc).
  - **Name / Summary**: the name is the issue title.
  - **Description**: in the text of the issue comments, starting with the first, but may be further down as goals/issues develop.
  - **Status:** the progress stage will be assigned as a Github Label
  - **Dependencies:** any other goals which are dependencies can be noted as links to the issue, using this format (as defined [in this discussion](https://github.com/jbenet/random-ideas/issues/37) and usably by [this module](https://github.com/noffle/github-dependency-crawl)):

    ```
    Depends on <link-to-goal/issue>
    ```

  - Pros: 
    - Clear, simple, everyone is used to it.
  - Cons:
  - Other:

**Comment by jbenet** [comment]
- @haadcode and @whyrusleeping please write up one for "Github Milestone as Milestone" (i can do it, too, but may be better to have all your pros)
- @diasdavid please write up one for "Github Labels as Milestone" (or whatever you wanted that was different).

**Comment by jbenet** [comment]
@flyingzumwalt any other mechanics pieces that you want to be clear on?

**Comment by flyingzumwalt** [comment]
Thanks @jbenet milestones is the main one where I wanted clarity for now because people seem to have strong examples. I'll be kicking up issues like this one soliciting advice/opinions and PRs suggesting edits to the PM doc section-by-section as we apply the Model to go-ipfs and to ipfs/pm.

**Comment by haadcode** [comment]
- **Github Milestones as Milestones:**
  - **Title**: name of the milestone
  - **Description**: description of the milestone
  - **Due date:** estimated completion date
  - **Goals:** list of goals of the milestone
  - **Progress:** shows how many goals of the milestone have been completed and how many are still open, shows percentage as well as absolute numbers
  - Pros: 
    - Clear, simple
    - Dedicated tool, ie. separate from Issues
    - Directly assign GH issues to milestones
    - Has s dedicated view in Github (for both: all milestones and individual ones)
  - Cons:
    - Not cross-repos :(

**Comment by haadcode** [comment]
I did some prototyping of generating roadmaps: https://github.com/haadcode/roadmap-generator

See an example of a generated roadmap here https://github.com/haadcode/roadmap-generator/blob/master/example/ROADMAP.md#ipfs-roadmap

**Comment by haadcode** [comment]
Having played around more, one note on "GH Milestones as Milestones" and "GH Labels as Milestones": they both fail to provide *one place* for all goals. You can't include a link in a document that takes you to "all goals of a milestone across all repos". 

As far as I can tell, "GH Issues as Milestones" is the only mechanism that provides that (you could do it with Github's global search but that would suck). Then again, "GH Issues as Milestones" is a lot of manual work atm, so it should be automated and should have all the up-to-date information in the first comment of the issue (ie. to give "all goals in one place" view).

**Comment by flyingzumwalt** [comment]
@haadcode do you think it would still be relatively easy to generate roadmaps from "GH Issues as Milestones"?  Would it be possible to make the roadmap include all the same stuff? I'm especially interested in progress indicators and Estimated Dates of Delivery.  Could one put that info in a GH Issue so that it can be parsed re-displayed in a roadmap? That seems tricky to me.

**Comment by jbenet** [comment]
for the "gh issues", can parse issues similar to how the deps stuff is doing it:
- parses: `Depends on <link-to-gh-issue>`
- https://github.com/jbenet/random-ideas/issues/37
- code for api parsing is here: https://github.com/noffle/github-dependency-crawl

So could do something like:

```
<milestone description>

Estimated Date: <date>

Goals:
- <link-to-gh-issue-here>
- <link-to-gh-issue-here>
- <link-to-gh-issue-here>
```
or something. maybe see what https://www.zenhub.com/blog/working-with-epics-in-github/ tracks.

**Comment by haadcode** [comment]
> @haadcode do you think it would still be relatively easy to generate roadmaps from "GH Issues as Milestones"? Would it be possible to make the roadmap include all the same stuff? I'm especially interested in progress indicators and Estimated Dates of Delivery. Could one put that info in a GH Issue so that it can be parsed re-displayed in a roadmap? That seems tricky to me.

On "GH Issues as Milestones": 

Parsing (reading) the information *from* Github is trivial (albeit slightly more complex). My main concern is how to *enter* data to Github. This is the important detail I keep mentioning re. duplication of data. 

If we would use "GH Issues as Milestones", one would need to: 
1) create an issue called "Milestone X" 
2) label it with something that indicates it's a milestone (and not a backlog item) 
3) input all the goals that are part of that milestone
4) input all other milestone details (description, ETA, etc)

How would we automate that? How/where would you define, for a computer, the issues that should be included in a milestone? How/where would you define the other milestone information? In order to automate the process, one would need a definition file somewhere and individually, explicitly say "this issue belongs to this milestone". And since it's a file, it probably needs to be saved somewhere, eg. git, which adds another layer to the workflow. In addition, we would need to define a milestone *data structure* so that our automation tools can read & write milestones within issues. This essentially makes the GH Issues sections our database for the milestones data.

Assume we find a way to automate the input. What happens when a milestone is changed (eg. a goal gets added or removed)? We need to a) update the milestone issue and b) re-generate the roadmap. With "GH Milestones as Milestones" (my current approach), we also need to re-generate the roadmap but milestones (as in GH Milestones) are updated automatically. For comparison, flow for "Remove a goal from a milestone" action:

- GH Issues as MS: edit the definition file (and probably need to commit/PR it) -> remove the milestone label from that particular issue in GH -> run 'milestones2issues" generator -> run roadmap-generator 
- GH Milestones as MS: remove the milestone assignment in GH issue -> run roadmap-generator

"GH Issues as Milestones" would also require us to use GH Labels to provide information per goal to which milestone they belong to (this comes "for free" with GH Labels as Milestones and GH Milestones as Milestones).

I'll play with this today and see how it could work, I'm sure I can find other ways to do it.

Another, slightly less important, but still a major down side of using "GH Issues as Milestones" is that in my head it breaks the model of a Backlog. If we consider GH Issues to be our Backlog, with "GH Issues as Milestones" milestones would live in the Backlog and they don't belong there in the model. This is not a biggie, but would be nice to make the distinction clear.

That all being said, "GH Issues as Milestones" has one major advantage: milestones can be discussed in a natural way. This is not possible with other mechanics brought up here. This feature may or may not be needed, but I reckon having a place for the discussion to happen would be beneficial in the long run considering we want to be able to do the *planning* distributed, over time.

So, putting all that together, what a "GH Issue as a Milestone" essentially does is collect the milestone information to one place providing a coherent and cross-repository view of the information. This is exactly what a roadmap would (should) do.

Regarding my previous comment:
> "GH Milestones as Milestones" and "GH Labels as Milestones": they both fail to provide one place for all goals. You can't include a link in a document that takes you to "all goals of a milestone across all repos".

I was thinking it'd be nice to have one place in Github, a url, that would be able to display milestone(s) per project. But obviously this is not possible with Github's interface, besides "GH Issues as Milestones". So what we end up doing is generating a customized views (roadmaps). I realized yesterday that this is exactly what roadmaps are for: put everything into one place, cross-repos, per project. And if they're saved in Github as .md we can link to them directly.

If we go back to definition of roadmaps:
- Project's roadmap is a view to *all milestones* across repos and *all goals for all milestones*.
- Organization's roadmap is a view to *all milestones* across projects and repos and *all goals for all milestones*.

Essentially, the roadmap replaces GH's Milestones view ("GH Milestones as Milestones") or GH's Issues (filtered) view ("GH Issues as Milestones" or "GH Labels as Milestones").

So this:
![screen shot 2016-08-31 at 13 11 13](https://cloud.githubusercontent.com/assets/7499694/18126891/95a22136-6f7d-11e6-8696-0913ef693d11.png)
*(Pros: looks really nice, it's a dedicated tool within GH and all of it is automatic. Cons: it can only display one repo at a time)*

Or this:
![screen shot 2016-08-31 at 13 17 39](https://cloud.githubusercontent.com/assets/7499694/18126899/9ec89f2e-6f7d-11e6-8c26-f1079fc4ff37.png)
Or this:
![screen shot 2016-08-31 at 13 17 45](https://cloud.githubusercontent.com/assets/7499694/18126910/a808ffa2-6f7d-11e6-8d00-58b1d21bcdeb.png)
*(Pros: looks almost as nice as the Milestone view, it's a tool within GH and most of it is automatic, visuals are customizable, can display cross-repo milestones. Cons: the input part, needs to be generated)*

Becomes this, with the exception that this one gathers everything across repos:
![screen shot 2016-08-31 at 13 06 14](https://cloud.githubusercontent.com/assets/7499694/18126918/afcb0488-6f7d-11e6-8e6b-3fdd54ef13aa.png)
*(Pros: gathers information across repos or across projects to one place, fully customizable. Cons: markdown is limited for creating appealing visuals, needs to be generated and saved as file somewhere)*

So, that's a lot... I'm still undecided. GH Milestones as Milestones feel natural and provide a nice interface to work with milestone. GH Issues as Milestones have more pros but at the same time is a little trickier to manage.

**Comment by haadcode** [comment]
> I thought @haadcode shared a link to something showing a GH milestone that includes issues from multiple GH repos and includes a progress indicator that includes all of the issues. Was I imagining that? Is that what labels-and-milestones does?

GH Milestones can't do cross-repo, so it's always per-repo view that you get. 

`labels-and-milestones` is a tool to sync same set of labels and milestones across multiple repos, which would be needed for all of these mechanics.

**Comment by haadcode** [comment]
Didn't get to try out "GH Issues as Milestones" with the roadmap-generator, but will do so tomorrow.

**Comment by flyingzumwalt** [comment]
This was a great discussion. We're making a solid push to use GH Milestones together with the labels-and-milestones sync tool.
