### ISSUE TITLE
todogroup.org - resources for open source management

### ISSUE THREAD

**Issue by diasdavid** [ipfs/pm#192]
Discovered today through @jlipps [tweet](https://twitter.com/jlipps/status/775778873766055936) that an organization  currently exists to explore, collaborate and share best practices and tools to manage open source projects in the open. I feel that this comes timely, as we are improving our management ourselves :)

The todogroup members are currently in a quartely meeting, will use this issue to track the outcomes. 

There are a bunch of articles are available of why and how some companies run and manage their Open Source projects, these are published on todogroup's blog http://todogroup.org/blog/

More about todogroup.org: http://todogroup.org/blog/todo-becomes-lf-collaborative-project/

**Comment by diasdavid** [comment]
captured this at https://github.com/ipfs/pm/pull/269

**Comment by RichardLitt** [comment]
I don't want this to just be a link; I'd love to join this group on behalf of Protocol Labs. I think we should give back, as well. @flyingzumwalt Would you be interested in joining, too?

**Comment by flyingzumwalt** [comment]
Their current list of members includes a lot of companies that we have expressed admiration for, and occasionally said things like "we should ask them how they handle <foo-challenge>"  So yeah. I'd be game for joining, though it's not clear how to do that.  

Process note: this issue is not framed as something that has a clear "finished" state, hence the confusion about whether it should be closed. @RichardLitt please either rename this issue and update the description or create a new Issue to track the work of applying to the todo group. That will reduce confusion.

**Comment by RichardLitt** [comment]
I've added my name to their Join list. We'll see if they get back to us. For now, let's close this.
