### ISSUE TITLE
Call to Discuss the PM Process

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#251]
IPFS Project Management Process Review: Nov 2016
===

[Notepad for the Call](https://hackmd.io/KYdgZgHCFgxgtAZgEYEMCM8AsAmAbKvKgKzo5HAnoCcsYixAJsUA)
[zoom](https://zoom.us/j/3339991818)
This discussion is part of https://github.com/ipfs/pm/issues/244 

## Review/History of the Document
The current Draft: https://github.com/ipfs/pm/pull/183/files

All the issues that track this work and discussions around it are tracked in the Milestone titled [Ratify New Project Management Model](https://github.com/ipfs/pm/milestone/1)

### First Draft
First Draft (@haad) gathers a lot of scattered information. It's contains a mix of what we were doing, what we should be doing, and what we might want to do.

* Defintes Goal, Milestone, Project
* Uses the term "Goal" instead of "Issue"
* Explains the Weekly Scrum Calls
* Delcares Quarterly cadence
* Hints at Kanban sensibilities (Backlog, Pipelines, etc)

### Second Draft
Second Draft (@flyingzumwalt) rearranges the info based on all the discussions on the related PRs and github issies. It attempts to use consistent language to accurately depict how we worked at the time.

* Consistent usage of terms: Goal, Milestone, Project
* Defines Roles: Project Lead, Project Manager, 
* Makes space for defining Maintainer, Contributor (otherwise the document completely ignores community contribution)
* Clarifies stuff around Backlog & Pipelines based on all the discussions

### Third Draft?
What do we need from this PM document?

Do we need it at all?

Who is the audience?

* Project Leads and Maintainers?
* Contributors?
* People relying on our code in their own projects?
* People who want to emulate our Project Management Process?

What is this document defining?

* Is it defining our Project Management Methodology? (do we really want to invent a new methodology)
* Is it defining our roles, responsibilities, and rhythm?
* Is it defining our interpretation of Kanban?

In the time since we authored Draft 2, we have converged on some conventions. What conventions have we converged on? How does this impact the PM Document?

### Project Manager vs Project Lead
Based on the description of responsibilities and power in the first 2 drafts, the Project Lead is simultaneously Scrum Master/Tech Lead, Project Manager, and one of the most prolific committers. This puts a huge burden on those people. It also forces them to act like a Benevolent Dictator.

### Governance: Benevolent Dictator vs. Consensus vs. ???
We don't have a governance model. That has led to a PM Process doc that barely even acknowledges the existence of a community of contributors beyond the core maintainers.

Meanwhile, the first two drafts strongly emphasize the Project Lead controlling the roadmap. They basically mandate that the Project Lead has to act like a Benevolent Dictator.

These factors don't set us up to grow the base of contributors and they discourage community engagement.

### Don't Go Chasing Waterfalls
Our approach to Milestone scheduling/deadlines (ie. the Roadmapping exercises) is basically waterfall. Does that match with reality? What should we be doing instead?

### How should we proceed towards ratifying a Project Management Process

* What do we need in order to collaborate well, deliver on time, incorporate new contributors, and scale our efforts horizontally?
* What do we need from this PM document? Do we need it at all?
* What timeline should we set for this work?

### If we Continue with this Document...

* Who is the audience?
* What is this document defining?
* What conventions have we converged on? How does this impact the PM Document?

**Comment by flyingzumwalt** [comment]
FYI: [HackMD pad with these notes](https://hackmd.io/MwVg7ADAHATDBsBaAnDAhsRAWAxvKiARoWMojACY44gBmAjMMjhCEA==)

**Comment by RichardLitt** [comment]
Thank you, @flyingzumwalt. Thank you especially for raising concerns about the PM roadmap and community engagement. I won't be able to make the call, but I look forward to reading the notes on this.

**Comment by flyingzumwalt** [comment]
The call is probably going to be rescheduled. Watch the doodle poll here: http://doodle.com/poll/659qpabx6vce3kfp#table

**Comment by haadcode** [comment]
Subscribing.

**Comment by flyingzumwalt** [comment]
cc @diasdavid @whyrusleeping @jbenet @em-ly Please try to read this before tomorrow's call. It will let us hit the ground running.

**Comment by haadcode** [comment]
Hi all, unfortunately I can't make it tonight as something else requires my attention at that time, sorry.

However, having prepared for this meeting earlier and read through all the discussion here, I'm only left with one question: what are we trying to do here? To me all these notes seem to say "let's blow up the PM process". What I'm having hard time with is to understand where all this is going.

I'll try to comment on the individual things here:

> Project Manager vs Project Lead
> Based on the description of responsibilities and power in the first 2 drafts, the Project Lead is simultaneously Scrum Master/Tech Lead, Project Manager, and one of the most prolific committers. This puts a huge burden on those people. It also forces them to act like a Benevolent Dictator.

The original idea was that we'd have a Project Manager to work with the Project Leads to ease that burden of doing *everything*. This didn't happen and I suppose we silently said we don't need it. Now, considering our resources, what options do we have? We can either accept the fact that these are our resources (ie. what we currently have) and define the roles accordingly (meaning, individuals have relative large workload in terms of project management) or we say "let's do it this way", add more resources to the projects (I'm doubtful this will happen easily) to help the Project Leads. But if we do that, what is the role of a Project Lead? That's when it becomes a dictator role. And that said, given how big (read: small) our individual projects are (excluding perhaps go-ipfs), is that a bad thing? Are these projects getting worked on and shipped unless a "benevolent dictator" makes sure they do? I'm not saying we *should* have benevolent dictators, but perhaps it's required at this point in time. As we grow, as the projects grow, perhaps then more distributed/split roles are needed.

> We don't have a governance model. That has led to a PM Process doc that barely even acknowledges the existence of a community of contributors beyond the core maintainers.
Meanwhile, the first two drafts strongly emphasize the Project Lead controlling the roadmap. They basically mandate that the Project Lead has to act like a Benevolent Dictator.
These factors don't set us up to grow the base of contributors and they discourage community engagement.

Touched this above a little, so continuing: how would you acknowledge the community contributors in the PM process? I believe it remains that unless there's a driving force behind any particular project, it will not be *managed*. I also never meant to write the original draft to NOT take community into consideration, but it never occurred to me that there's something obviously wrong in the PM process itself by leaving them out. So I'm gonna roll this back to you: *why* is the fact that a Project Lead controls the roadmap a bad thing (I believe we phrased it in the doc in a way that the Project Lead works with the community to make sure community's priorities/voice are heard, but I might remember wrong)? *What* in the PM process *requires* to define the role of a contributor?

> Our approach to Milestone scheduling/deadlines (ie. the Roadmapping exercises) is basically waterfall. Does that match with reality? What should we be doing instead?

This, I think, is unfortunate. In my original proposal (in Lisbon) I spoke highly against doing this and proposing something to alleviate the need to do the process like we do. I tried to convey that into the first draft of the PM process. 

To me it doesn't make sense to plan our roadmaps on weekly granularity, it doesn't make sense to plan them with deadlines (unless there's a specific need, or beyond the end-of-Q milestone) and it definitely doesn't make sense to plan them on such a granular level as we have done so far (we have mixed goals with milestones and this was obvious in the planning meeting in Toronto). I think what is needed is to train ourselves on *how* to structure projects into manageable milestones and goals.

My idea was that our PM process allows us the flexibility we need to make quick changes to our roadmaps. From waterfall to lean(-ish), so that we're not planned out for weeks in advance and try to hit the dates/milestones exactly as planned (this rarely works).

> What do we need in order to collaborate well, deliver on time, incorporate new contributors, and scale our efforts horizontally?

All of these questions were addressed/solutions proposed in my talk in Lisbon but since we need to ask them, I think we have failed in our PM process definition :( For the sake of record, the notes from my talk are here: https://gist.github.com/haadcode/70bd15c6d85ad637d223a8c03785f89d.

> What do we need from this PM document? Do we need it at all?

I believe we're on the right track but given the lack of attention (from everyone), it's not moving anywhere (and hasn't since... August-ish?).

---

Given everything @flyingzumwalt has asked, given how the process hasn't developed over the past months, I believe the root question we need to ask is, why didn't the PM process get implemented as it was written? Is the PM process as it is written not what we *want* or was there other reasons to not follow it? We spent countless of hours discussing it, writing it and re-writing it, so I was under the impression we're on the same page. So somewhere, somehow, we've misaligned our thoughts on this.

Apologies if this sounds quick, blunt, harsh or gloomy.

**Comment by flyingzumwalt** [comment]
Notes from Call to Discuss the PM Process 16-Nov 2016
====

# Agenda

* Check in about the process - why has it stalled?
  * labels-and-milestones
  * roadmap generator
* What do we need from this document? Who is the Audience?
* How do we finish this?
* Project Manager vs. Facilitator
  * Stakeholder engagement
  * Following up with committers
* Weekly Calls
* Governance: Benevolent Dictator vs. Consensus vs. ???
* Getting away from the Waterfall
    * REFORMAT Roadmap exercise as a product design + Kanban training 
    * General org changes Product Design Thinking


# Links

- https://github.com/ipfs/pm/issues/251
- https://github.com/protocol/team-week-2016-Q4/issues/37
- https://github.com/ipfs/pm/pull/183

## Notes
Process Check in
Why have things stalled?
 - Permissions were an issue (@flyingzumwalt didn't have access to the repos, and now someone needs to ensure his access is revoked.)

What is the purpose of this document:
 - This document clarifies how we're going to organize and how that will be accomplished
 - It gives us a basic framing for how projects are structured across the board.

Who is the audience for this document?
 - Project leads, across the board.
 - Other contributors need to be in the loop as well so that they can jump into leadership and help take over.
 - Anyone that contributes to the projects needs to be able to pick up the mechanics of our process so that they can jump in.

How do we move forward next?
 - Merge the current draft and go through another revision round?
 - Isn't this already in use?
 - We've bootstraped out PM process so far, time to upgrade.
 - We don't yet have the one document that shows Juan where things are going.
 - There are still a few things that need to be patched, people are approaching it on their own process (ex: `backlog`, `help wanted`)
 - A lot of questions on the issue that we should address
https://github.com/ipfs/pm/issues/251

Project Manager & Facilitator responsibilities
 - There is a lot under the PM title that is still needs to be covered, following up on assigned tasks, and engaging with stakeholders.
 - We all have a responsibility to engage with stakeholders.
 - We need to set a pattern for engaging with stakeholders that's open to future product owners.

Weekly Calls
 - Purpose of the call is to check in with contributors about what they've committed to that week, and spending that time updating the board with what people are working on.
 - That is the primary venue for those calls. If that doesn't take place during the call, project leads have to follow up on those assigned tasks on their own time, which can become a major time sink.
 - Agenda for weekly calls:
     - There should only be an agenda for the All Hands call
     - There doesn't need to be an agenda for the project calls, it should be focused grooming the Waffle board

Governance: Benevolent Dictator vs. Consensus vs. ???
 - @haadcode: It's totally nature for a young project like ours to need a Benevolent Dictator
 - There is a lot more discuss that needs to take place around this.


Getting away from the Waterfall
 - For Q1 Want to reformat our RoadMap exercise away from the waterfall method
 - There may be some changes in the document to reflect the sort of changes that @flyingzumwalt wants to see.

## Action Items:
 - [ ] @flyingzumwalt to sanity check with Nicola about if this works with IPLD
    Cautious: Nicola's time is limited and doesn't have a lot to spare.

**Comment by flyingzumwalt** [comment]
I've uploaded a recording of the call to google drive at https://drive.google.com/open?id=0B7snS36pEV4HaE9aT29Hc2d0OGc
cc @haadcode

**Comment by flyingzumwalt** [comment]
FYI I plan to re-watch the video (to get back in the swing from my vacation) and post more thorough notes based on the second watching.
