### ISSUE TITLE
Sprint template: move agenda below notes

### ISSUE THREAD

**Issue by lgierth** [ipfs/pm#266]
It's common that participants edit the agenda while the meeting is ongoing, and for me personally that's very very distracting when taking notes. It messes with my notetaking rhythm.

Alternatively: once the meeting has started, the notetaker is the only one allowed to edit the document.

**Comment by lgierth** [comment]
I failed to describe why it's so distracting: editors show a fixed pane of lines, e.g. lines 30 to 59, and when someone adds lines above that, what was previously lines 30 to 59, is now lines 35 to 64. Stuff moves while I'm typing and that's where my notetaking rhythm goes over board.

**Comment by RichardLitt** [comment]
I would do something different: Move the notes below the agenda, and agree to not write in the agenda at all after it has started. 

There is another option: Don't separate out the agenda and the notes. Instead, take notes directly in the agenda. This has the benefit that people can see what is being note-taken while they are looking at the pad. Currently, the note taker often has to do unpraised work below, and people do not help out - they look at the agenda, and then don't write anything else. Ideally, we should all be writing notes as it goes along, so that the note taker can actually join in the conversation. 

If we need to know what is next, we can see below the current section of the notes, where any current items haven't been done yet. 

I think allowing only one notetaker is not a good move; it explicitly disincentivizes participation, which isn't what we want at all.

**Comment by diasdavid** [comment]
I haven't seen or heard any more complaints about this, I believe that now we understand the role of a notetaker well and even though sometimes a couple of agenda items are added in the middle of the call, it is not anymore the case where multiple people are always writing at the same time. 

Closing this one, reopen later if needed.
