### ISSUE TITLE
Guide on How to Use milestones, labels and roadmaps tools

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#289]
Write a guide for project/endeavor leads on how to use labels-and-milestones and roadmap-generator

Also include links to relevant reference info, especially the PM process doc and conventions about issue labels.

**Comment by flyingzumwalt** [comment]
cc @em-ly @RichardLitt can you help me with writing this?

Sample user / test user: @hsanjuan

**Comment by RichardLitt** [comment]
Happy to help. I wasn't able to get labels-and-milestones working, though, so I'm not sure if I am the best to write it. I could work through it with you?

**Comment by hsanjuan** [comment]
It doesn't have to be a step-by-step or something super detailed. Basically I'd like to see just a collection of PM policy items which we aim to follow. i.e. Having @RichardLitt standard-readme is one of such practices (I think), as well as setting up waffle instead of github projects. Common cross-project labels, common repo-badges etc and any tips of how you (PM focused people) would like everyone else to handle projects from a PM perspective.

**Comment by RichardLitt** [comment]
Regarding README standards, take a look at [ipfs/devtools](https://github.com/ipfs/devtools). I've made a template for IPLD, and am moving on to multiformats today. I've been working on [a linter](https://github.com/RichardLitt/standard-readme-linter-regex) with options as a way of making it easy to test a README in a repo and see how it is. I'm not entirely comfortable with using an automatic generator - some linted things need to be checked manually for the most part - but I'm working on that.

Labels are foreign to me at the moment, as our process doc has taken shape and we don't have a label config. These are the only ones I enforce across repos: https://github.com/ipfs/community/blob/master/dev/tools/github/githubLabels.json.
