### ISSUE TITLE
Sprint: January 2-8

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#303]
_For information about these calls and how they work, read [the ipfs/pm README](https://github.com/ipfs/pm)._

[Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com)

Zoom and Stream links will be updated directly before the calls. Links to them will also be dropped in IRC, at the start of each call. If the link below seems to link to this issue, the link has not been updated yet.

### Monday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
All Hands Call | @em-ly  | 9:00 **17:00** 18:00  | [agenda and notes](https://hackmd.io/GYI2FMRBWEFoBsAGA7ADjgFnARiXNFATgBM4RxglwEBDNAZhxQGMg===)
go-ipfs        | @whyrusleeping  | 10:00 **18:00** 19:00 | [agenda and notes](https://hackmd.io/CwZgbApgjA7ADDAtGAHDAnI4AzATAY0QCMoRCR4xdt8cJsYg)
apps on IPFS   | @haadcode        | 10:30 **18:30** 19:30 | [agenda and notes](https://hackmd.io/AwdgjAnMAcIMwFoDGBDJAzBAWJAjRKcAbBAtBEmCtMACYCsoIQA=)
js-ipfs        | @diasdavid      | 11:00 **19:00** 20:00 | [agenda and notes](https://hackmd.io/CYTgRgLArADMBsBaCwBMxkzCRAOAjAMYyIgT4BmhAzLgKZ27zBA=)
libp2p         | @diasdavid      | 11:30 **19:30** 20:30 | [agenda and notes](https://hackmd.io/KYDgDAhgTARgnAFgLRQGZ2EhBGA7NpOAZlwBMkwQQFSBjYGhVXIA)

### Friday

Endeavour      | Lead            | Time (PST - UTC - CET) | Pad
:------------: | :-------------: | :--------------------: | :----:
IPLD           | @nicola         | 9:00 **17:00** 18:00 | [agenda and notes](https://hackmd.io/OwFgJgHADCCcDMBaEAjFBTZdiNgNgGMAmRKAM3QgEMwBGWlW9IoA)

Please add any agenda items you have to the pad before the project-specific sprint call starts.

**Comment by RichardLitt** [comment]
I will not be around for this one. To announce them in IRC, use `sprint-helper announce`. If you need help, use `sprint-helper help`. It'll involve copying the links for notes, zoom, and the stream manually.

**Comment by dignifiedquire** [comment]
I won't be around for this one

**Comment by flyingzumwalt** [comment]
I recommend using these calls on the 2nd to do Q4 Community/Project Retrospectives. I won't be able to join the calls (traveling), but it's a perfect time for those discussions. I'll watch the recordings. I know @diasdavid is already preparing to do this. @whyrusleeping and @haadcode can you do this in your calls? Is someone willing to lead a community retrospective on the all-hands? @RichardLitt

**Comment by em-ly** [comment]
I'm marked as the call lead for the all-hands, but also am traveling that day and will be cutting it close. Does anyone else feel like they can lead the community retrospective call during that time?

**Comment by kevina** [comment]
Sorry, for the late notice, but I am unlikely to be around for the go-ipfs call.  I will be available on IRC later in the day if anyone needs me.

**Comment by diasdavid** [comment]
### Hi all :) 

I'll be attending and leading the js-ipfs and libp2p calls today as usual, however, since everyone is coming from holidays and getting back up to speed, I believe it is the best for us to use the time to evaluate how we performed last quarter. I know, it requires time and preparation for a really good retrospective and I do hope that with more time, everyone that has been contributing can bring their more formal feedback, but there are a list of things we can quickly evaluate, namely:

- Sprints pace (how is the 1 week thing doing for everyone?)
- Waffle - Is waffle useful for you? Did it enable you to contribute more? Tells us how you use it or how you would like to be using it
- Are the roadmap documents helpful?
- How about support for all the users, did you feel you got your questions answered? What were the pain points when trying to figure out something?
- How does everyone feel with what we've achieved so far?
- Anything else you feel you should bring to the table :)

With respect to the little time we have available and to enable everyone to have time to present their feedback, try to frame your point with:

- What was good
- What was confusing, less productive
- What do you want to continue or to see started

Excited to see everyone again in this new exciting turn around the Sun ☀️ Thank you!

**Comment by dignifiedquire** [comment]
I will try and join for js-ipfs and libp2p

**Comment by diasdavid** [comment]
### All hands notes: https://github.com/ipfs/pm/pull/304

**Comment by johndpope** [comment]
Sorry to drop in on this issue. Has anyone looked at some quick wins with ipfs and pip /and or  other package managers?  I watch the weeks go by and ipfs has yet to take over the datacenter world. or has it?   https://github.com/pypa/pip/issues/4215

**Comment by hsanjuan** [comment]
Hi @johndpope . I think most discussions related to this can be found in ipfs/notes. i.e.:

https://github.com/ipfs/notes/issues/171
https://github.com/ipfs/notes/issues/2

**Comment by RichardLitt** [comment]
It looks like IPLD will not happen today. If anyone has anything they want to talk about, feel free to raise it here or in the sprint schedule for the next sprint, happening in two weeks from now. Apologies for not noticing this sooner!

**Comment by jbenet** [comment]
@johndpope the gist is: we need help doing so! there's a ton to do!
