### ISSUE TITLE
Auto-assign moderator and notetaker for All Hands calls

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/pm#586]
In the past we had the sprint helper automatically assigning moderator and notetaker based on [this list](https://github.com/ipfs/pm#facilitators-and-notetakers)

but that hasn't worked for a few months. We should reinstate it, but 
- what list should it source from?
- how should it work?
- Who can do this?

**Comment by flyingzumwalt** [comment]
this is a duplicate of #483.

**Comment by pmthomps** [comment]
Submitted [PR #13](https://github.com/ipfs/node-github-issue-bot/pull/13) with fix.  

Uses the [same list as before](https://github.com/ipfs/pm/blob/master/README.md#moderators-and-notetakers).  The list will need to be reinstated since it was removed.  I'll submit a separate PR for that.

This uses the same logic as before.  Searches for latest Calls Issue in the ipfs/pm repo -> Grabs the Moderator specified in that issue -> Uses the next name in the above list for the next call moderator.

**Comment by diasdavid** [comment]
@VictorBjelkholm has fixed this. This is now done through the fixed sprint helper. sprint-helper picks a moderator and notetaker from https://github.com/ipfs/pm/blob/master/templates/all-hands-facilitators.json
