### ISSUE TITLE
Weekly Roundup

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/pm#73]
[eminence](//github.com/eminence) wrote [here](https://github.com/ipfs/pm/issues/67#issuecomment-162960821):

> Hi all. As an experiment, I'd like to make the following proposal:

> At the end of this sprint (next Monday), try to pick 1 thing that you accomplished that you would like to call attention to. I think a simple annotation with an asterisk will do (though if you want to say a few things about it, feel free). The idea is that someone (I volunteer for this sprint) will gather these things together and produce a short summary/blog designed to be read by the wider IPFS community (not just people closely following development). This idea is modeled after https://this-week-in-rust.org/.

> It will be TDB how to publish this summary/blog, but perhaps we can make use http://ipfs.io/blog/ or another repo in the ipfs org. Let's start simple, get feedback, and iterate!

> If you have any idea on this idea itself, I think it might be best to discuss elsewhere (as not to go off topic in this issue). I am `achin` on IRC.

> Thanks!

I think this is a fantastic idea. What do you think?

**Comment by Dignifiedquire** [comment]
💯💯💯 yes very much in favor

**Comment by chriscool** [comment]
Yeah, the blog definitely need some content and that would be a great way to start.

**Comment by lgierth** [comment]
Yes let's do it, sounds great!

**Comment by fazo96** [comment]
Very nice idea! And it solves a big problem: sometimes it's hard to understand what has been going on when out of the loop :+1:

**Comment by jbenet** [comment]
Absolutely. would be great. let's learn a lot from the Rust community. like this: https://this-week-in-rust.org/

**Comment by eminence** [comment]
Hi all, here is a draft of the first edition:

------------------
Welcome to the first edition of the IPFS Weekly Roundup!  [IPFS](https://ipfs.io/) is a new hypermedia distribution protocol, addressed by content and identities, aiming to make the web faster, safer, and more open.  In these posts, we will try to highlight some of development that happened in the past week.  For anyone looking to get involved, follow the embedded hyperlinks, search the wealth of information on [github](https://github.com/ipfs) or join us on [IRC](http://webchat.freenode.net/?channels=ipfs) (#ipfs on the Freenode network).

Here's a summary of what happened during the December 7 [Sprint](https://github.com/ipfs/pm/issues/67) :

* @whyrusleeping  shipped IPFS version 0.3.10!  It contains 74 new [commits](https://github.com/ipfs/go-ipfs/compare/v0.3.9...v0.3.10) since the previous version and you can get it [here](https://ipfs.io/docs/install/).
* npm on IPFS!  `registry-mirror` is a new tool that enables distributed discovery of npm modules by fetching and caching the latest state of npm through IPNS.  For more info, see this [blog post](http://blog.daviddias.me/2015/12/08/stellar-module-management) by @diasdavid .
* In the same vein,  @robcat and @fazo96 have done great work to integrate IPFS with pacman (the package manager for Arch Linux).  For more details, see [this](https://github.com/ipfs/notes/issues/84) active discussion.
* @jbenet released a new tool/library called [dnslink](https://github.com/jbenet/go-dnslink) that makes it easy to resolve dns links (special TXT records in a domain name that can point to paths, like an IPFS path)
* @Dignifiedquire has been working on an attractive new distribution page for IPFS, which will be the new landing page to download all things IPFS.  You can see the latest screenshots [here](https://github.com/ipfs/distributions/issues/11).
* On the infrastructure side of things, @lgierth has [bootstrapped](https://github.com/ipfs/infrastructure/pull/135) two new storage, each with 17 TB of disk space!  
* @RichardLitt continues to [work on](https://github.com/ipfs/api/pull/13) some much needed API documentation.

For a sneak peek at the coming week, check out the [Dec 14](https://github.com/ipfs/pm/issues/74) sprint issue

Thanks, and see you next week!


------------------

Discussion points:  

* Do we like the name "IPFS Weekly Roundup" ?
* I opted not to use a plural pronoun, instead mentioning people by name ("whyrusleeping shipped 0.3.10" instead of "we shipped 0.3.10"), since I thought it would be nice to give out proper recognition, but this doesn't quite capture the fact that lot of this work involved multiple people.  Thoughts?
* Does it make sense to use PRs to develop and iterate on these each week? If so, how?
* Where to publish?  To the blog?

**Comment by harlantwood** [comment]
Forgot to star it but in the past week I wrote a bit of nodejs code that spins up a fresh IPFS node, sets it to a known ID,  and publishes to IPNS using that node ID.

https://github.com/ipfs/project-repos/pull/11

**Comment by jedahan** [comment]
Seeing the lead contributor names is more encouraging than 'we', imo, from the outside. Maybe at the end of each roundup, you can have a generated list of all the people who contributed with a thank you, or at least a 'There were dozens of more contributors this week, more than we could fit in a short round-up, but be assured we couldn't have done nearly as much without your help!' or somesuch

**Comment by Dignifiedquire** [comment]
Thanks a lot @eminence for doing this, some thoughts below

* I think `IPFS Weekly` would be a better name. 
* For publishing, I suggest a repo `ipfs/ipfs-weekly` with markdown files. We can worry about adding different publishing formats on top of that easily later.
* Tbh I don't see the need for every item to be directly linked to who did it, but it does make sense in the connection of the "Sync" section. In that spirit I would suggest expanding this a bit more to add these sections
  * `Spec Updates`: Merged PRs and important discussions on ipfs/specs
  * `Releases`: A list of all tools and implementations under the ipfs umbrella that got new releases in the last week, with links to download and changelog

**Comment by RichardLitt** [comment]
> Do we like the name "IPFS Weekly Roundup" ?

I think "IPFS Weekly" works just fine.

I agree with a repo with markdown files, too. Hypothetically, that could be an issue in this repository, but I don't think it's really project management, so a repo elsewhere makes sense to me. A newsletter would also be good. We've been meaning to get on this for a while, I think, but I might be thinking of something else. But a repo, for now, with merges and the subsequent notification to everyone who watches the repo for now - that sounds good. 

I think using names is smart, too. We should definitely make a tool to get all contributors each week. @rvagg just made a tool that might work for this: [new-contributors](https://github.com/rvagg/new-contributors). I'd be happy to mess with it // find another tool // create another tool to see if we can get a readout of all contributors for the past week. What do you think of this? I know Meteor does something similar with their newsletters, thanking everyone who had a good PR. 

> Does it make sense to use PRs to develop and iterate on these each week? If so, how?

If we move to another repo, yes. I don't really want to have this in PM, because this is a specific repo for management. A PR could be made every monday, and then comments could be taken until tuesday, when it is posted. Perhaps?

> Where to publish? To the blog?

Blog would be good. 

I also agree with @Dignifiedquire's ideas for 'Spec Updates' and 'Releases'. Sounds good.

**Comment by jedahan** [comment]
@rvagg's tool looks more robust, but a quick-a-dirty way to get a list of contributors in the last week for all repositories in repos/:

```shell
contributors() {
  tmplog=$(mktemp)
  for repo in repos/*; do
    ( cd "$${repo}" && git log --format="%aN," --since=1.week ) >> $tmplog
  done
  sort -fu $tmplog | tr '\n' ' ' | sed 's/\(.*\)\,/\1\n/'
  rm $tmplog
}
```

**Comment by eminence** [comment]
Great comments all, thanks!   Here's a second draft

Regarding the 'Spec Updates' section, currently our ipfs/specs repo is pretty quiet, so we might not have this section each week.  I think the idea is to call attention to spec updates that deserve visibility (like the RFC section from this-week-in-rust) so instead, I'm trying an 'Active Discussion' section that brings together interesting (and active) topics from all of the relevant repos (specs, notes, archives, community, etc).  However for the time being, I've only re-categorized what was already selected from your syncup (I didn't go out and find new stuff to include)


------------------
Welcome to the first edition of IPFS Weekly!  [IPFS](https://ipfs.io/) is a new hypermedia distribution protocol, addressed by content and identities, aiming to make the web faster, safer, and more open.  In these posts, we will try to highlight some of development that happened in the past week.  For anyone looking to get involved, follow the embedded hyperlinks, search the wealth of information on [github](https://github.com/ipfs) or join us on [IRC](http://webchat.freenode.net/?channels=ipfs) (#ipfs on the Freenode network).

Here's a summary of what happened during the December 7 [Sprint](https://github.com/ipfs/pm/issues/67) :

### Releases
* @whyrusleeping  shipped IPFS version 0.3.10!  It contains 74 new [commits](https://github.com/ipfs/go-ipfs/compare/v0.3.9...v0.3.10) since the previous version and you can get it [here](https://ipfs.io/docs/install/).
* npm on IPFS!  `registry-mirror` is a new tool that enables distributed discovery of npm modules by fetching and caching the latest state of npm through IPNS.  For more info, see this [blog post](http://blog.daviddias.me/2015/12/08/stellar-module-management) by @diasdavid .
* @jbenet released a new tool/library called [dnslink](https://github.com/jbenet/go-dnslink) that makes it easy to resolve dns links (special TXT records in a domain name that can point to paths, like an IPFS path)

### Updates
* On the infrastructure side of things, @lgierth has [bootstrapped](https://github.com/ipfs/infrastructure/pull/135) two new storage, each with 17 TB of disk space!  
* @RichardLitt continues to [work on](https://github.com/ipfs/api/pull/13) some much needed API documentation.
* @harlantwood wrote a bit of [nodejs code](https://github.com/ipfs/project-repos/pull/11) that spins up a fresh IPFS node, sets it to a known ID, and publishes to IPNS using that node 

### Spec Updates
* The new IPFS Linked Data (IPLD) spec is actively being iterated on in the specs repository.  Join the discussion [here!](https://github.com/ipfs/specs/pull/37)

### Active stuff
* @robcat and @fazo96 have done great work to integrate IPFS with pacman (the package manager for Arch Linux).  For more details, see [this](https://github.com/ipfs/notes/issues/84) active discussion.
* @Dignifiedquire has been working on an attractive new distribution page for IPFS, which will be the new landing page to download all things IPFS.  You can see the latest screenshots [here](https://github.com/ipfs/distributions/issues/11).

### Contributors

Across the entire IPFS github organization, the following people have made contributions in the past week!

* Christian Couder
* David Dias
* dignifiedquire
* Enrico Fasoli, 
* Friedel Ziegelmayer, 
* greenkeeperio-bot, 
* Harlan T Wood, 
* Ian Preston, 
* Jeromy, 
* Juan Benet, 
* Kyle Drake, 
* Lars Gierth, 
* RainerWasserfuhr, 
* Richard Littauer, 
* Teo Sartori


For a sneak peek at the coming week, check out the [Dec 14](https://github.com/ipfs/pm/issues/74) sprint issue

Thanks, and see you next week!


------------------

**Comment by Dignifiedquire** [comment]
Looking really good, a note on the contrib list, greenkeeper is a bot and can be removed and I'm twice on there once as Friedel and once as dignifiedquire

**Comment by eminence** [comment]
robots need love, too!

ok, I edited the above post to remove those two entries

**Comment by jbenet** [comment]
My feedback:

- **this is great and going to be a huge part if our community. so many people will be so thankful**
- i'd be down to cross post it to the blog. we can do posts there in that repo, or in a separate weekly repo.
- we can also cross-post it to an issue in https://github.com/ipfs/ipfs which hundreds of people watch. they would appreciate the summaries.
- instead of "Here's a summary of what happened during the December 7 Sprint :" maybe "Here are some highlights of what happened during the December 7 Sprint :" -- because this is not a summary, it's highlights. 
- maybe link the whole "[December 7 Sprint](#)" (not just Sprint)
- i'd probably cut things like "@RichardLitt continues to work on some much needed API documentation." -- so many people are actively working on so many things that we should either enumerate all the WIPs or avoid it. I think we should keep the weekly roundup for (a) things that are released/done or have reached some milestone, (b) things that need {collabs, input, review, and so on}.
- maybe instead "@RichardLitt has reached a draft1 of the API documentation." (if that's accurate, @RichardLitt)
- "the following people have made contributions in the past week!" -- **can we include everyone who commented on issues? often, issue comments are _major, pivotal_ contributions, and those should be captured!** the github api can yield this information. and this should happen across all repos.
- **i would use people's github handles, not their proper names. this is because handles are used all over the place.** if want real names, use `- @jbenet (Juan Benet)`
- "but this doesn't quite capture the fact that lot of this work involved multiple people. Thoughts?" in general, err on the side of giving credit to everyone involved. when people do the lion's share, mention them first. (or even something like "@whyrusleeping and several others ... " if relevant. in the case of a release can link to the changelog which credits individually... but anyway don't sweat this)
- add a line somewhere (either end of first paragraph or end of email) requesting feedback on the Weekly with a link to a github issue in the Weekly repo to capture that feedback. 
- in general, try linking larger phrases instead of single words. easier to notice + click on links.
- in general, try highlighting _why_ something is cool. for example:
- on "@robcat and @fazo96 have done great work to integrate IPFS with pacman (the package manager for Arch Linux). For more details, see this active discussion." maybe say that they've actually integrated it, like maybe "@robcat and @fazo96 have done great work integrating IPFS with pacman (the package manager for Arch Linux). They can now install arch packages straight from IPFS! For more details, see this active discussion."
- on "npm on IPFS! registry-mirror is a new tool that enables distributed discovery of npm modules by fetching and caching the latest state of npm through IPNS. For more info, see this blog post by @diasdavid ." maybe "npm on IPFS! registry-mirror is a new tool that enables distributed discovery and installing of npm modules by caching npm through IPNS. You can now install modules directly from your friends' computers, even while offline! For more info, see this blog post by @diasdavid. " or something.


Another format for different topics that dont always get updates is:

> ### Updates
> - **[(api)](https://github.com/ipfs/api)** @RichardLitt continues to work on some much needed API documentation.
> - **[(infrastructure)](https://github.com/ipfs/infrastructure)** On the infrastructure side of things, @lgierth has bootstrapped two new storage, each with 17 TB of disk space!
> - **[(specs)](https://github.com/ipfs/specs)** The new IPFS Linked Data (IPLD) spec is actively being iterated on in the specs repository. Join the discussion here!

**Comment by RichardLitt** [comment]
:+1: to all of the above.

> maybe instead "@RichardLitt has reached a draft1 of the API documentation." (if that's accurate, @RichardLitt)

Agreed; only items that are done. As for this, yeah, that's true at this point. Still more work to do, though, as always!

**Comment by eminence** [comment]
Thanks @jbenet for the comments on style and phrasing!  Below is a 3rd draft.   :+1: to your comments in general, but here are a few specific replies:

> so many people are actively working on so many things that we should either enumerate all the WIPs or avoid it. I think we should keep the weekly roundup for (a) things that are released/done or have reached some milestone, (b) things that need {collabs, input, review, and so on}.

I am in partial agreement.  One of the things that prompted me to think about producing a summary like this is that I often read the sprint notes and was left wondering "what does all this mean?".   So I was in fact hoping to highlight on-going WIP stuff, even knowing that I wouldn't be mentioning everything.


> can we include everyone who commented on issues? often, issue comments are major, pivotal contributions, and those should be captured!

To include every comment seems like too much to me.  The person asking for a clarification in the support repo, for example, perhaps does not need a special mention here.  I do agree that we could include people who have made really important comments (for example, mildred's feedback in the IPLD PR), but I have to admit that I'm not really prepared to attempt to make this value judgement for every comment made in a week.

> add a line somewhere (either end of first paragraph or end of email) requesting feedback on the Weekly with a link to a github issue in the Weekly repo to capture that feedback.

Absolutely.  Feedback is important stuff.  Let's add this once we know where we want feedback to go.  

Once we get a repo, we should check-in a tool that will get the list of weekly contributors, and map their emails to github usernames.  

------------------
Welcome to the first edition of IPFS Weekly!  [IPFS](https://ipfs.io/) is a new hypermedia distribution protocol, addressed by content and identities, aiming to make the web faster, safer, and more open.  In these posts, we will try to highlight some of development that happened in the past week.  For anyone looking to get involved, follow the embedded hyperlinks, search the wealth of information on [github](https://github.com/ipfs) or join us on [IRC](http://webchat.freenode.net/?channels=ipfs) (#ipfs on the Freenode network).

Here are some highlights of what happened during the [December 7 Sprint](https://github.com/ipfs/pm/issues/67) :

### Releases
* @whyrusleeping  shipped IPFS version 0.3.10!  It contains [74 new commits](https://github.com/ipfs/go-ipfs/compare/v0.3.9...v0.3.10) since the previous version and you can [get it here](https://ipfs.io/docs/install/).
* npm on IPFS!  `registry-mirror` is a new tool that enables distributed discovery of npm modules by fetching and caching the latest state of npm through IPNS.  For more info, see this [blog post](http://blog.daviddias.me/2015/12/08/stellar-module-management) by @diasdavid .
* @jbenet released a new tool/library called [dnslink](https://github.com/jbenet/go-dnslink) that makes it easy to resolve dns links (special TXT records in a domain name that can point to paths, like an IPFS path)

### Updates
* [**(infrastructure)**](https://github.com/ipfs/infrastructure) On the infrastructure side of things, @lgierth has [bootstrapped](https://github.com/ipfs/infrastructure/pull/135) two new storage, each with 17 TB of disk space!  
* [**(api)**](https://github.com/ipfs/api) @RichardLitt has [reached a draft 1]((https://github.com/ipfs/api/pull/13) of the much needed API documentation.
* @harlantwood wrote a bit of [nodejs code](https://github.com/ipfs/project-repos/pull/11) that spins up a fresh IPFS node, sets it to a known ID, and publishes to IPNS using that node 
* [**(specs)**](https://github.com/ipfs/specs) The new IPFS Linked Data (IPLD) spec is actively being iterated on in the specs repository.  Join the discussion [here!](https://github.com/ipfs/specs/pull/37)

### Active stuff
* @robcat and @fazo96 have done great work integrating IPFS with pacman (the package manager for Arch Linux).  They can now install arch packages straight from IPFS!  For more details, see [this active discussion](https://github.com/ipfs/notes/issues/84).
* @Dignifiedquire has been working on an attractive new distribution page for IPFS, which will be the new landing page to download all things IPFS.  You can see the [latest screenshots here](https://github.com/ipfs/distributions/issues/11).

### Contributors

Across the entire IPFS github organization, the following people have made contributions in the past week!

* Christian Couder
* David Dias
* Enrico Fasoli, 
* Friedel Ziegelmayer, 
* Harlan T Wood, 
* Ian Preston, 
* Jeromy, 
* Juan Benet, 
* Kyle Drake, 
* Lars Gierth, 
* RainerWasserfuhr, 
* Richard Littauer, 
* Teo Sartori


For a sneak peek at the coming week, check out the [Dec 14](https://github.com/ipfs/pm/issues/74) sprint issue

Thanks, and see you next week!


------------------


We're getting close!  Thanks for all the feedback!

**Comment by jbenet** [comment]
> I am in partial agreement. One of the things that prompted me to think about producing a summary like this is that I often read the sprint notes and was left wondering "what does all this mean?". So I was in fact hoping to highlight on-going WIP stuff, even knowing that I wouldn't be mentioning everything.

yes but i think people are going to start looking at these summaries as "the view" into what's going on.

> To include every comment seems like too much to me. The person asking for a clarification in the support repo, for example, perhaps does not need a special mention here. I do agree that we could include people who have made really important comments (for example, mildred's feedback in the IPLD PR), but I have to admit that I'm not really prepared to attempt to make this value judgement for every comment made in a week.

agreed. but i think actually raw comment numbers is a "good enough" proxy. sure there's some noise, but it's mostly signal after double digits. we don't have people posting willy-nilly here-- it's not the github culture. (and they'd be reported if so).

in any case, i do not feel right having a list saying "these people contributed to ipfs" that fails to include the _very valuable_ discussions. Maybe make it "these people contributed code to ipfs", with a note stating the obvious "Many more people have contributed in discussions on GitHub and IRC."

> Across the entire IPFS github organization, the following people have made contributions in the past week!

Are you sure this list is right? is it grabbing the commit logs of every repo, or what? it looks way too small. several names come to mind not listed.

This list is important to get right. By creating "a way to recognize and give credit" we sign ourselves up for the "must make it a fair and accurate account" part. I think that either we have it right, or we should not at all. Recognizing some and not others will make people feel unappreciated. unfairness -- even if understandably complicated -- [is very socially problematic](https://www.youtube.com/watch?v=HL45pVdsRvE).

One possibly simple way out of this: if this is not from commits, but just the people who participated in the sprint, then instead of:

> Across the entire IPFS github organization, the following people have made contributions in the past week!

say:

> The following people participated in this week's community sprint:

with a link to the pm repo for how to participate. This may be ok, and encourage people to participate in the sprint syncs, and posting things to this repo.

--- 

@eminence sorry to put make more work out of this, but since this is such a good idea that i want to make a very important part of our sprints + process, i want to make sure we get this right.

**Comment by eminence** [comment]
ok, ill try to pull a list of every single comment made last week.  once we have that, we can take a look at its length and go from there

regarding the list of contributors, i'm not sure it's right.  i cloned ever repo (all 66 of them) and ran the little [bash snipped](https://github.com/ipfs/pm/issues/73#issuecomment-164830923) from @jedahan .  in reviewing it, i see that it just pulls the *last week*'s worth of commits, which is a different time period than the previous sprint, so perhaps that is the reason for the discrepancy.  who did you expect to see on the list but wasn't there?

**Comment by RichardLitt** [comment]
This looks great to me, @eminence!

I added a repo, and filled it full of the comments and suggestions from this thread. I think we should be good to go. https://github.com/ipfs/roundups

Can we post this Weekly, now? I don't want it to become stale, there's been a lot of work on it!

**Comment by RichardLitt** [comment]
Moved to github.com/ipfs/weekly!
